# Generated by Django 3.1.6 on 2021-02-19 21:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210217_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-published',)},
        ),
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
                ('publishedmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
