# Generated by Django 3.1.6 on 2021-02-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='caralho', max_length=100),
            preserve_default=False,
        ),
    ]
